name: Update GPD-Payments XSD

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - SANP3.5.0
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - SANP3.5.0


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-file:
    name: Update GPD-Payments XSD
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # open a PR on GPD-Payments repo
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # prepare XSD template for GPD repo
      - name: Modify file
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/xsd"
          cp ${GITHUB_WORKSPACE}/wsdl/xsd/paForNode.xsd ${GITHUB_WORKSPACE}/xsd/paForNode.xsd
      - name: Create pull request
        uses: jacopocarlini/action-pull-request-another-repo@main
        with:
          source_folder: 'xsd'
          destination_repo: 'pagopa/pagopa-gpd-payments'
          destination_folder: 'src/main/resources'
          destination_base_branch: 'main'
          destination_head_branch: 'XSD-update'
          user_email: 'github-bot@pagopa.it'
          user_name: 'pagopa-github-bot'
          allow_force_push: 'true'
